/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.HoaDonCT;
import repo.HoaDonCTRepo;
import repo.HoaDonRepo;

/**
 *
 * @author admin
 */
public class HoaDonView extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    private HoaDonRepo hdRepo;
    private HoaDonCTRepo hdctRepo;
    private int pageHd = 1;
    private int limitHd = 5;
    //
    private int pageHdct = 1;
    private int limitHdct = 5;

    public HoaDonView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.hdRepo = new HoaDonRepo();
        this.hdctRepo = new HoaDonCTRepo();

        this.lblPageHD.setText(this.pageHd + "");
        this.lblPageHdct.setText(this.pageHdct + "");

        this.loadTableHD();
    }

    private void loadTableHD() {
        ArrayList<HoaDon> ds = this.hdRepo.paging(this.pageHd, this.limitHd);
        DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
        dtm.setRowCount(0);
        for (HoaDon h : ds) {
            Object[] row = {
                h.getMaHD(),
                h.getNv().getHoTen(),
                h.getKh().getHoTen(),
                h.getNgayTao(),
                h.getTongTien(),
                h.getSoTienGiamGia(),
                h.getHinhThucThanhToan(),
                h.getGhiChu(),
                h.getThanhTien(),
                h.getTrangThai() == 0 ? "Chưa thanh toán" : "Đã thanh toán"
            };
            dtm.addRow(row);
        }
    }

    private void loadTableHdct() {
        int rowIndex = this.tblHoaDon.getSelectedRow();
        if (rowIndex == -1) {
            return;
        }
        int id_hd = this.hdRepo.getIdHd(rowIndex);
        ArrayList<HoaDonCT> ds = this.hdctRepo.paging(id_hd, pageHdct, limitHdct);
        DefaultTableModel dtm = (DefaultTableModel) this.tblHdct.getModel();
        dtm.setRowCount(0);
        for (HoaDonCT h : ds) {
            Object[] row = {
                h.getId(),
                h.getSpct().getMaSPCT(),
                h.getSoLuong(),
                h.getSpct().getDonGia()
            };
            dtm.addRow(row);
        }
    }

    private int getTotalPagesHD() {
        int totalItems = this.hdRepo.getTotalItems();
        return (int) Math.ceil((double) totalItems / limitHd);
    }

    private int getTotalPagesHdct() {
        int totalItems = this.hdctRepo.getTotalItems();
        return (int) Math.ceil((double) totalItems / limitHdct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSanPham = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnBackHD = new javax.swing.JButton();
        lblPageHD = new javax.swing.JLabel();
        btnNextHD = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoiTimKiem = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHdct = new javax.swing.JTable();
        btnBackHdct = new javax.swing.JButton();
        btnNextHdct = new javax.swing.JButton();
        lblPageHdct = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnSanPham.setBackground(new java.awt.Color(236, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaHD", "Tên NV", "Tên KH", "Ngày tạo", "Tổng tiền", "Tiền giảm", "HTTT", "Ghi chú", "Thành tiền", "Trạng thái"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblHoaDon);

        btnBackHD.setText("<<");
        btnBackHD.setEnabled(false);
        btnBackHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHDActionPerformed(evt);
            }
        });

        lblPageHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageHD.setText("0");

        btnNextHD.setText(">>");
        btnNextHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHDActionPerformed(evt);
            }
        });

        jLabel20.setText("Mã HD");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoiTimKiem.setText("Làm mới");
        btnLamMoiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoiTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackHD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPageHD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNextHD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane6)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnLamMoiTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackHD)
                    .addComponent(btnNextHD)
                    .addComponent(lblPageHD))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn chi tiết"));

        tblHdct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_Hdct", "Mã SPCT", "Số lượng", "Giá hiện hành"
            }
        ));
        tblHdct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHdctMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblHdct);

        btnBackHdct.setText("<<");
        btnBackHdct.setEnabled(false);
        btnBackHdct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHdctActionPerformed(evt);
            }
        });

        btnNextHdct.setText(">>");
        btnNextHdct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHdctActionPerformed(evt);
            }
        });

        lblPageHdct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageHdct.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackHdct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPageHdct, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNextHdct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackHdct)
                    .addComponent(btnNextHdct)
                    .addComponent(lblPageHdct))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHdctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHdctMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHdctMouseClicked

    private void btnLamMoiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiTimKiemActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");
        this.loadTableHD();
    }//GEN-LAST:event_btnLamMoiTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String searchMa = txtTimKiem.getText().toLowerCase();
        if (searchMa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập dữ liệu cần tìm");
            return;
        }
        ArrayList<HoaDon> ds = hdRepo.findAll();
        DefaultTableModel dtm = (DefaultTableModel) tblHoaDon.getModel();
        dtm.setRowCount(0);
        int check = 0;
        for (HoaDon h : ds) {
            if (h.getMaHD().toLowerCase().contains(searchMa)) {
                check = 1;
                Object[] row = {
                    h.getMaHD(),
                    h.getNv().getHoTen(),
                    h.getKh().getHoTen(),
                    h.getNgayTao(),
                    h.getTongTien(),
                    h.getSoTienGiamGia(),
                    h.getHinhThucThanhToan(),
                    h.getGhiChu(),
                    h.getThanhTien(),
                    h.getTrangThai() == 0 ? "Chưa thanh toán" : "Đã thanh toán"
                };
                dtm.addRow(row);
            }
        }
        if (check == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn!");
            this.loadTableHD();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnNextHdctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHdctActionPerformed
        // TODO add your handling code here:
        int totalPages = getTotalPagesHdct(); // Phương thức để lấy tổng số trang
        if (this.pageHdct < totalPages) {
            this.pageHdct++;
            this.lblPageHdct.setText(String.valueOf(this.pageHdct));
            this.loadTableHdct();
        }
        // Cập nhật trạng thái nút Back
        this.btnBackHdct.setEnabled(this.pageHdct > 1);
        // Cập nhật trạng thái nút Next
        this.btnNextHdct.setEnabled(this.pageHdct < totalPages);
    }//GEN-LAST:event_btnNextHdctActionPerformed

    private void btnBackHdctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHdctActionPerformed
        // TODO add your handling code here:
        if (this.pageHdct > 1) {
            this.pageHdct--;
            this.lblPageHdct.setText(String.valueOf(this.pageHdct));
            this.loadTableHdct();
        }

        // Cập nhật trạng thái nút Back
        this.btnBackHdct.setEnabled(this.pageHdct > 1);
        // Cập nhật trạng thái nút Next
        int totalPages = getTotalPagesHdct();
        this.btnNextHdct.setEnabled(this.pageHdct < totalPages);
    }//GEN-LAST:event_btnBackHdctActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        this.loadTableHdct();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnBackHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHDActionPerformed
        // TODO add your handling code here:
        if (this.pageHd > 1) {
            this.pageHd--;
            this.lblPageHD.setText(String.valueOf(this.pageHd));
            this.loadTableHD();
        }

        // Cập nhật trạng thái nút Back
        this.btnBackHD.setEnabled(this.pageHd > 1);
        // Cập nhật trạng thái nút Next
        int totalPages = getTotalPagesHD();
        this.btnNextHD.setEnabled(this.pageHd < totalPages);
    }//GEN-LAST:event_btnBackHDActionPerformed

    private void btnNextHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHDActionPerformed
        // TODO add your handling code here:
        int totalPages = getTotalPagesHD(); // Phương thức để lấy tổng số trang
        if (this.pageHd < totalPages) {
            this.pageHd++;
            this.lblPageHD.setText(String.valueOf(this.pageHd));
            this.loadTableHD();
        }
        // Cập nhật trạng thái nút Back
        this.btnBackHD.setEnabled(this.pageHd > 1);
        // Cập nhật trạng thái nút Next
        this.btnNextHD.setEnabled(this.pageHd < totalPages);
    }//GEN-LAST:event_btnNextHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackHD;
    private javax.swing.JButton btnBackHdct;
    private javax.swing.JButton btnLamMoiTimKiem;
    private javax.swing.JButton btnNextHD;
    private javax.swing.JButton btnNextHdct;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblPageHD;
    private javax.swing.JLabel lblPageHdct;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JTable tblHdct;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

}
