/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhuyenMai;
import repo.KhuyenMaiRepo;

/**
 *
 * @author admin
 */
public class KhuyenMaiView extends javax.swing.JFrame {

    private int page = 1;
    private int limit = 5;

    private KhuyenMaiRepo kmRepo;
    List<KhuyenMai> listKM = new ArrayList<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat currencyFormat = new DecimalFormat("#,##0");

    /**
     * Creates new form MainJFrame
     */
    public KhuyenMaiView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.kmRepo = new KhuyenMaiRepo();
        listKM = this.kmRepo.getAllKhuyenMai();
//        fillToFormKM(0);
        this.maAuto();
        this.loadTable();
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchByMaKH();
            }
        });
//        lblPage.setText(this.page + "");

    }

    private void loadTable() {
//        ArrayList<KhuyenMai> ds = this.kmRepo.paging(page, limit);
        ArrayList<KhuyenMai> ds = this.kmRepo.getAllKhuyenMai();
        DefaultTableModel dtm = (DefaultTableModel) this.tblKhuyenMai.getModel();
        dtm.setRowCount(0);
        for (KhuyenMai km : ds) {
            Object[] row = {
                km.getMaKM(),
                km.getTenChienDich(),
                km.getMucGiamGia(),
                km.getHoaDonToiThieu(),
                km.getSoLuong(),
                km.getSoHoaDonAD(),
                km.getNgayBD(),
                km.getNgayKT(),
                km.getTrangThai() == 0 ? "Đã hết hạn" : "Đang hoạt động"
            };
            dtm.addRow(row);
        }
    }

    private int getTotalPages() {
        int totalItems = this.kmRepo.getTotalItems();
        return (int) Math.ceil((double) totalItems / limit);
    }

    private void searchByMaKH() {
        String searchMaKH = txtTimKiem.getText().trim();
        DefaultTableModel searchModel = new DefaultTableModel();
        searchModel = (DefaultTableModel) tblKhuyenMai.getModel();
        searchModel.setRowCount(0);

        for (KhuyenMai km : listKM) {
            if (km.getMaKM().toLowerCase().contains(searchMaKH.toLowerCase())) {
                searchModel.addRow(new Object[]{
                    km.getMaKM(),
                    km.getTenChienDich(),
                    km.getMucGiamGia(),
                    km.getHoaDonToiThieu(),
                    km.getSoLuong(),
                    km.getSoHoaDonAD(),
                    km.getNgayBD(),
                    km.getNgayKT(),
                    km.getTrangThai() == 0 ? "Đã hết hạn" : "Đang hoạt động",});
            }
        }
        tblKhuyenMai.setModel(searchModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhuyenMai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenChienDich = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMucGiamGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHDTT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dcsBatDau = new com.toedter.calendar.JDateChooser();
        dcsKetThuc = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemKM = new javax.swing.JButton();
        btnSuaKM = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnKetThucKM = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rdoDangHoatDong = new javax.swing.JRadioButton();
        rdoDaHetHan = new javax.swing.JRadioButton();
        btnMa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 242, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo mã khuyến mại"));

        jLabel2.setText("Mã khuyến mại");

        txtMaKhuyenMai.setEditable(false);

        jLabel3.setText("Tên chiến dịch");

        jLabel4.setText("Mức giảm giá (%)");

        jLabel5.setText("Hóa đơn tối thiểu (VND)");

        jLabel6.setText("Thời gian bắt đầu");

        jLabel7.setText("Thời gian kết thúc");

        jLabel8.setText("Số lượng");

        btnThemKM.setText("Thêm Khuyến Mại");
        btnThemKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKMActionPerformed(evt);
            }
        });

        btnSuaKM.setText("Sửa Khuyến Mại");
        btnSuaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKMActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR FORM");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnKetThucKM.setText("Kết thúc Khuyến Mại");
        btnKetThucKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucKMActionPerformed(evt);
            }
        });

        jLabel9.setText("Trạng thái");

        buttonGroup1.add(rdoDangHoatDong);
        rdoDangHoatDong.setSelected(true);
        rdoDangHoatDong.setText("Đang hoạt động");

        buttonGroup1.add(rdoDaHetHan);
        rdoDaHetHan.setText("Đã hết hạn");

        btnMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenChienDich)
                    .addComponent(txtMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhuyenMai)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtHDTT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnMa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcsBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcsKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoDangHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rdoDaHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnThemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnSuaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnKetThucKM, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenChienDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHDTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcsBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcsKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rdoDangHoatDong)
                            .addComponent(rdoDaHetHan))))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKM)
                    .addComponent(btnSuaKM)
                    .addComponent(btnClear)
                    .addComponent(btnKetThucKM))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khuyến mại"));

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên CD", "Mức giảm giá (%)", "Hóa đơn tối thiểu (VND)", "Số lượng", "Số HD đã AD", "Ngày BD", "Ngày KT", "Trạng thái"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        jLabel20.setText("Tìm theo mã KM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHUYẾN MẠI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        // TODO add your handling code here:
        int viTri = -1;
        viTri = tblKhuyenMai.getSelectedRow();
        String trangThaiStr = this.tblKhuyenMai.getValueAt(viTri, 8).toString();
        if (trangThaiStr.equals("Đang hoạt động")) {
            this.rdoDangHoatDong.setSelected(true);
        } else {
            this.rdoDaHetHan.setSelected(true);
        }
        fillToFormKM(viTri);
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void btnThemKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKMActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm khuyến mại không?", "Xác nhận yêu cầu", JOptionPane.YES_NO_CANCEL_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            KhuyenMai km = getKhuyenMai();
            if (km == null) {
                JOptionPane.showMessageDialog(this, "Mời bạn thử lại");
                return;
            }
            if (this.kmRepo.checkTrungMa(txtMaKhuyenMai.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Mã KM đã tồn tại");
                return;
            }
            this.kmRepo.InsertKhuyenMai(km);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable();

        }
    }//GEN-LAST:event_btnThemKMActionPerformed

    private void btnSuaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKMActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn chỉnh sửa khuyến mại không?", "Xác nhận yêu cầu", JOptionPane.YES_NO_CANCEL_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int vtri = tblKhuyenMai.getSelectedRow();
            if (vtri == -1) {
                JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng muốn chỉnh sửa");
                return;
            }
            KhuyenMai km = getKhuyenMai();
            if (km == null) {
                JOptionPane.showMessageDialog(this, "Mời bạn thử lại");
                return;
            }
            int id_km = this.kmRepo.getIdKM(vtri);
            this.kmRepo.UpdateKhuyenMai(km, id_km);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTable();
//                this.kmRepo.UpdateTrangThaiKM(km);
//                listKM = this.kmRepo.getAllKhuyenMai();
//                fillToFormKM(0);

        }
    }//GEN-LAST:event_btnSuaKMActionPerformed

    private void btnMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaActionPerformed
        // TODO add your handling code here:
        this.maAuto();
    }//GEN-LAST:event_btnMaActionPerformed

    private void btnKetThucKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucKMActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn chỉnh sửa khuyến mại không?", "Xác nhận yêu cầu", JOptionPane.YES_NO_CANCEL_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int vtri = tblKhuyenMai.getSelectedRow();
            if (vtri < 0) {
                JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng muốn kết thúc");
                return;
            }
            int id_km = kmRepo.getIdKM(vtri);
            this.kmRepo.UpdateTrangThaiKMTrucTiep(id_km);
            JOptionPane.showMessageDialog(this, "Kết thúc khuyến mại thành công");
            listKM = this.kmRepo.getAllKhuyenMai();
            loadTable();
        }
    }//GEN-LAST:event_btnKetThucKMActionPerformed

    private void clearForm() {
        this.txtMaKhuyenMai.setText("");
        this.txtTenChienDich.setText("");
        this.txtMucGiamGia.setText("");
        this.txtHDTT.setText("");
        dcsBatDau.setDate(null);
        dcsKetThuc.setDate(null);
        dcsBatDau.setEnabled(true);
        this.txtSoLuong.setText("");
    }

    public void fillToFormKM(int index) {
        txtMaKhuyenMai.setText(tblKhuyenMai.getValueAt(index, 0).toString());
        txtTenChienDich.setText(tblKhuyenMai.getValueAt(index, 1).toString());
        txtMucGiamGia.setText(tblKhuyenMai.getValueAt(index, 2).toString());
        txtHDTT.setText(tblKhuyenMai.getValueAt(index, 3).toString());
        txtSoLuong.setText(tblKhuyenMai.getValueAt(index, 4).toString());
        Date NgayBatDau = (Date) tblKhuyenMai.getValueAt(index, 6);
        dcsBatDau.setDate(NgayBatDau);
        Date NgayKetThuc = (Date) tblKhuyenMai.getValueAt(index, 7);
        dcsKetThuc.setDate(NgayKetThuc);
        if (tblKhuyenMai.getValueAt(index, 8).toString().equals("Đã hết hạn")) {
            rdoDaHetHan.isSelected();
        } else {
            rdoDangHoatDong.isSelected();
        }
    }

    public KhuyenMai getKhuyenMai() {
        if (txtTenChienDich.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống tên chiến dịch");
            return null;
        }
        if (txtMucGiamGia.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống mức giảm giá");
            return null;
        }
        int MucGiam = 0;
        try {
            MucGiam = Integer.parseInt(txtMucGiamGia.getText());
            if (MucGiam < 0) {
                JOptionPane.showMessageDialog(this, "Mức giảm không được âm");
                return null;
            }
            // Nếu yêu cầu chỉ đúng khi MucGiam >= 0 và <= 50
            if (MucGiam > 50) {
                JOptionPane.showMessageDialog(this, "Mức giảm phải nhỏ hơn hoặc bằng 50");
                return null;
            }
            // ...

            if (txtHDTT.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn không được để trống Hóa đơn tối thiểu");
                return null;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mức giảm phải là số nguyên");
            return null;
        }
        float HDTT = 0.0f; // Khởi tạo giá trị HDTT ở đây
        try {
            HDTT = Float.parseFloat(txtHDTT.getText());
            if (HDTT < MucGiam) {
                JOptionPane.showMessageDialog(this, "Hóa đơn tối thiểu phải lớn hơn mức giảm");
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hóa đơn tối thiểu phải là số thực");
            return null;
        }
        if (txtSoLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống số lượng");
            return null;
        }
        int soLuong;
        try {
            soLuong = Integer.parseInt(txtSoLuong.getText());
            if (soLuong < 0 || soLuong > 200) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0 và bé hơn 200");
                return null;
            }
//            int xx = tblKhuyenMai.getSelectedRow();
//            if (xx >= 0 && soLuong <= listKM.get(xx).getSoHoaDonAD()) {
//                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn bằng số hóa đơn đã áp dụng");
//                return null;
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            e.printStackTrace();
            return null;
        }
        Date NgayBatDau = dcsBatDau.getDate();
        Date NgayKetThuc = dcsKetThuc.getDate();
        Date currentDate = new Date();
        if (dcsBatDau.isEnabled()) {
            if (NgayBatDau.before(currentDate)) {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải lớn hơn ngày hôm nay");
                return null;
            }
        }
        if (NgayKetThuc.before(NgayBatDau)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải lớn hơn ngày bắt đầu");
            return null;
        }
        int trangThai = 1; // 1 là trạng thái "Đang hoạt động", 0 là trạng thái "Đã hết hạn"
        if (rdoDangHoatDong.isSelected()) {
            trangThai = 1;
        } else {
            trangThai = 0;
        }
        KhuyenMai km = new KhuyenMai();
        km.setMaKM(txtMaKhuyenMai.getText());
        km.setTenChienDich(txtTenChienDich.getText());
        km.setMucGiamGia(MucGiam);
        km.setNgayBD(dcsBatDau.getDate());
        km.setNgayKT(dcsKetThuc.getDate());
        km.setHoaDonToiThieu(HDTT);
        km.setSoLuong(soLuong);
        km.setTrangThai(trangThai);
        return km;
    }

    private void maAuto() {
        ArrayList<KhuyenMai> ds = kmRepo.getAllKhuyenMai();
        if (ds.size() == 0) {
            txtMaKhuyenMai.setText("KM001");
        } else {
            int viTriCuoi = ds.size() - 1;
            KhuyenMai k = ds.get(viTriCuoi);
            String ma = k.getMaKM();
            int so = Integer.valueOf(ma.substring(2));
            so++;
            String id = "KM00" + so;
            txtMaKhuyenMai.setText(id);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMaiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKetThucKM;
    private javax.swing.JButton btnMa;
    private javax.swing.JButton btnSuaKM;
    private javax.swing.JButton btnThemKM;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dcsBatDau;
    private com.toedter.calendar.JDateChooser dcsKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoDaHetHan;
    private javax.swing.JRadioButton rdoDangHoatDong;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtHDTT;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtMucGiamGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenChienDich;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
