/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Size;
import repo.MauSacRepo;
import repo.SizeRepo;
import repo.ThuongHieuRepo;
/**
 *
 * @author USER
 */
public class KichThuocView extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private SizeRepo ktRepo = new SizeRepo();

    public KichThuocView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Màu Sắc");
        setLocationRelativeTo(null);
        maSizeAuto();
        loadTableSize(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTrangThai = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTH = new javax.swing.JTextField();
        txtTenTH = new javax.swing.JTextField();
        btnAutoMaTH = new javax.swing.JButton();
        rdoHD = new javax.swing.JRadioButton();
        rdoKHD = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKichThuoc = new javax.swing.JTable();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Nhập Thông Tin Kích Thước\n\n"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã KT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Trạng Thái");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên Kích Thước");

        txtMaTH.setEditable(false);

        btnAutoMaTH.setText("Auto");
        btnAutoMaTH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutoMaTHMouseClicked(evt);
            }
        });

        buttonGroupTrangThai.add(rdoHD);
        rdoHD.setSelected(true);
        rdoHD.setText("Hoạt Động");

        buttonGroupTrangThai.add(rdoKHD);
        rdoKHD.setText("Không Hoạt Động");

        btnThem.setText("Thêm");
        btnThem.setPreferredSize(new java.awt.Dimension(72, 35));
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setPreferredSize(new java.awt.Dimension(72, 35));
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseClicked(evt);
            }
        });

        btnClearForm.setText("Clear Form");
        btnClearForm.setPreferredSize(new java.awt.Dimension(72, 35));
        btnClearForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutoMaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(rdoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdoKHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtTenTH, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAutoMaTH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenTH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdoKHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Các Thương Hiệu"));

        tblKichThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã", "Tên Thương Hiệu", "Trạng Thái"
            }
        ));
        tblKichThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKichThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKichThuoc);

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Hoạt động", "Không hoạt động" }));
        cbbTrangThai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTrangThaiItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Trạng thái");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoMaTHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutoMaTHMouseClicked
        // TODO add your handling code here:
        maSizeAuto();
    }//GEN-LAST:event_btnAutoMaTHMouseClicked
    private void clearForm() {
        maSizeAuto();
        viTriChon = -1;
        txtTenTH.setText("");
        rdoHD.setSelected(true);
        tblKichThuoc.clearSelection();
    }

    private void loadTableSize(int trangThai) {//0 hoạt động,1 không hoạt đọng, 2 hiển thị tất cả
        DefaultTableModel dtm = (DefaultTableModel) tblKichThuoc.getModel();
        dtm.setRowCount(0);
        ArrayList<Size> ds = ktRepo.findAllSizeSX();
        for (Size a : ds) {
            if (trangThai == 2) {
                Object[] row = {
                    a.getId(), a.getMaSize(), a.getTenSize(), a.getTrangThai() == 0 ? "Hoạt động" : "Không hoạt động"
                };
                dtm.addRow(row);
            } else if (trangThai == 0) {
                if (a.getTrangThai() == 0) {
                    Object[] row = {
                        a.getId(), a.getMaSize(), a.getTenSize(), a.getTrangThai() == 0 ? "Hoạt động" : "Không hoạt động"
                    };
                    dtm.addRow(row);
                }
            } else {
                if (a.getTrangThai() == 1) {
                    Object[] row = {
                        a.getId(), a.getMaSize(), a.getTenSize(), a.getTrangThai() == 0 ? "Hoạt động" : "Không hoạt động"
                    };
                    dtm.addRow(row);
                }
            }
        }
    }

    private void maSizeAuto() {
        ArrayList<Size> ds = ktRepo.findAllSizeSX(); // Sắp xếp maMau tăng dần
        if (ds.size() == 0) {
            txtMaTH.setText("SZ001");
        } else {
            int viTriCuoi = ds.size() - 1;

            Size s = ds.get(viTriCuoi);
            String maMau = s.getMaSize();
            int so = Integer.valueOf(maMau.substring(2));
            so++;
            String maTHM = "SZ" + String.format("%03d", so);
            txtMaTH.setText(maTHM);
        }
    }
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        Size s = getForm(0);//truyền vào 0 cn thêm, 1 là cn cập nhật
        if (s == null) {
            return;
        }
        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm size không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == 0) {
            ktRepo.creat(s);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadTableSize(2);
            clearForm();
        } else {
            return;
        }
    }//GEN-LAST:event_btnThemMouseClicked
    public Size getForm(int chucNang) {//truyền vào 0 cn thêm, 1 là cn cập nhật
        ArrayList<Size> ds = ktRepo.findAllSizeSX();
        String ma = txtMaTH.getText();
        if (chucNang == 0) {
            for (Size a : ds) {
                if (a.getMaSize().equals(ma)) {
                    JOptionPane.showMessageDialog(this, "Mã size này đã tồn tại!");
                    return null;
                }
            }
        }
        String ten = txtTenTH.getText();
        if (ten.trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Tên size không được để trống!");
            return null;
        }
        if (ten.length() > 100) {
            JOptionPane.showMessageDialog(this, "Tên size không được dài quá 100 kí tự!");
            return null;
        }
        for (Size a : ds) {
            if (chucNang == 1) {
                if (a.getTenSize()== null && a.getMaSize().equals(tblKichThuoc.getValueAt(viTriChon, 1))) {
                    break;
                }
            }
            if (a.getTenSize().equals(ten)) {
                JOptionPane.showMessageDialog(this, "Tên size này đã tồn tại!");
                return null;
            }
        }
        int trangThai;
        if (rdoHD.isSelected()) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }

        Size s = new Size();
        String maSizeKhiChon = (String) tblKichThuoc.getValueAt(viTriChon, 1);
        if (chucNang == 0) {
            s.setMaSize(ma);
        } else {
            s.setMaSize(maSizeKhiChon);
        }
        s.setTenSize(ten);
        s.setTrangThai(trangThai);
        return s;
    }
    private int viTriChon = -1;
    private void btnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseClicked
        // TODO add your handling code here:
        if (viTriChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng hãy chọn 1 màu trước khi cập nhật!");
            return;
        }
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận cập nhật!", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == 0) {
            String maSizeKhiChon = (String) tblKichThuoc.getValueAt(viTriChon, 1);
            ktRepo.update_TenSize_VeNull(maSizeKhiChon);
            Size s = getForm(1);
            if (s == null) {
                return;
            }
            ktRepo.update(s);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadTableSize(2);
            clearForm();
        } else {
            return;
        }
    }//GEN-LAST:event_btnCapNhatMouseClicked

    private void btnClearFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFormMouseClicked
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearFormMouseClicked

    private void tblKichThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKichThuocMouseClicked
        // TODO add your handling code here:
        int viTri = tblKichThuoc.getSelectedRow();
        if (viTri == -1) {
            return;
        }
        viTriChon = viTri;
        txtMaTH.setText((String) tblKichThuoc.getValueAt(viTri, 1));
        txtTenTH.setText((String) tblKichThuoc.getValueAt(viTri, 2));
        if (tblKichThuoc.getValueAt(viTri, 3).equals("Hoạt động")) {
            rdoHD.setSelected(true);
        } else {
            rdoKHD.setSelected(true);
        }
    }//GEN-LAST:event_tblKichThuocMouseClicked

    private void cbbTrangThaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTrangThaiItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String trangThai = (String) cbbTrangThai.getSelectedItem();
            if (trangThai == "Tất cả") {
                loadTableSize(2);
            } else if (trangThai == "Hoạt động") {
                loadTableSize(0);
            } else {
                loadTableSize(1);
            }
        }
    }//GEN-LAST:event_cbbTrangThaiItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KichThuocView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KichThuocView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KichThuocView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KichThuocView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KichThuocView dialog = new KichThuocView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoMaTH;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroupTrangThai;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoHD;
    private javax.swing.JRadioButton rdoKHD;
    private javax.swing.JTable tblKichThuoc;
    private javax.swing.JTextField txtMaTH;
    private javax.swing.JTextField txtTenTH;
    // End of variables declaration//GEN-END:variables
}
