/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ThongKe;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import repo.ThongKeRepo;

/**
 *
 * @author USER
 */
public class ThongKeView extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeView
     */
    private ThongKeRepo thongKeRepo = new ThongKeRepo();

    public ThongKeView() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        doanhThu(1);
        tongHoaDon(1);
        tongSoSanPham(1);
        bieuDo(1);
    }

    private void bieuDo(int check) {//1 từ trước đến nay,2 ngày hôm nay, 3 tháng này, 4 năm nay, 5 tìm kiếm trong khoảng ngày
        // Tạo dữ liệu biểu đồ
        DefaultCategoryDataset dataset = createDataset(check);

        // Tạo biểu đồ
        JFreeChart chart = ChartFactory.createBarChart(
                "Số lượng sản phẩm đã được bán ra",
                "Sản phẩm",
                "Số lượng",
                dataset, PlotOrientation.VERTICAL, // Hướng của biểu đồ
                false, // Không hiển thị chú thích (legend)
                true, // Tooltips
                false
        );

        // Tạo ChartPanel và thêm vào bieuDoPanel
        ChartPanel chartPanel = new ChartPanel(chart);

//        bieuDoPanel.add(chartPanel, BorderLayout.CENTER);
        bieuDoPanel.removeAll(); // Xóa tất cả các thành phần trong bieuDoPanel
        bieuDoPanel.setLayout(new BorderLayout());
        bieuDoPanel.add(chartPanel, BorderLayout.CENTER);
        bieuDoPanel.revalidate(); // Cập nhật lại bieuDoPanel
        bieuDoPanel.repaint(); // Vẽ lại bieuDoPanel
    }

    private DefaultCategoryDataset createDataset(int check) {//1 từ trước đến nay,2 ngày hôm nay, 3 tháng này, 4 năm nay, 5 tìm kiếm trong khoảng ngày
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        ArrayList<ThongKe> ds = new ArrayList<>();
        ds.clear();
        if (check == 1) {
            ds = thongKeRepo.thongKeTatCaSanPhamBanRaTuTruocDenNay();
        } else if (check == 2) {
            ds = thongKeRepo.thongKeTatCaSanPhamBanRaTrongHomNay();
        } else if (check == 3) {
            ds = thongKeRepo.thongKeTatCaSanPhamBanRaTrongThangNay();
        } else if (check == 4) {
            ds = thongKeRepo.thongKeTatCaSanPhamBanRaTrongNamNay();
        } else if (check == 5) {
            ds = thongKeRepo.thongKeTatCaSanPhamBanTrongKhoangThoiGian(txtNgayBD.getDate(), txtNgayKT.getDate());
        }
        // Thêm dữ liệu mẫu
        for (ThongKe a : ds) {
            dataset.addValue(a.getSoLuong(), "Sản phẩm", a.getTenSP());
        }
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbThongKe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        txtNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTongSP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTongHD = new javax.swing.JLabel();
        bieuDoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Thống kê");

        cbbThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Từ trước tới nay", "Ngày hôm nay", "Tháng này", "Năm nay" }));
        cbbThongKe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThongKeItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Từ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Đến");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Doanh thu :");

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoanhThu.setText("_ _ _");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tổng sản phẩm đã bán :");

        lblTongSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongSP.setText("_ _ _");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tổng số hóa đơn :");

        lblTongHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongHD.setText("_ _ _");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTongSP))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTongHD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTim)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbbThongKe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bieuDoPanelLayout = new javax.swing.GroupLayout(bieuDoPanel);
        bieuDoPanel.setLayout(bieuDoPanelLayout);
        bieuDoPanelLayout.setHorizontalGroup(
            bieuDoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bieuDoPanelLayout.setVerticalGroup(
            bieuDoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bieuDoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bieuDoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbThongKeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThongKeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String luaChon = (String) cbbThongKe.getSelectedItem();
            if (luaChon == "Từ trước tới nay") {
                doanhThu(1);
                tongHoaDon(1);
                tongSoSanPham(1);
                bieuDo(1);
            } else if (luaChon == "Ngày hôm nay") {
                doanhThu(2);
                tongHoaDon(2);
                tongSoSanPham(2);
                bieuDo(2);
            } else if (luaChon == "Tháng này") {
                doanhThu(3);
                tongHoaDon(3);
                tongSoSanPham(3);
                bieuDo(3);
            } else {
                doanhThu(4);
                tongHoaDon(4);
                tongSoSanPham(4);
                bieuDo(4);
            }
        }
    }//GEN-LAST:event_cbbThongKeItemStateChanged

    private void doanhThu(int check) {//1 từ trước đến nay, 2 hôm nay, 3 tháng này, 4 năm nay, 5 tìm kiếm trong khoảng ngày
        DecimalFormat df = new DecimalFormat("#,###.00");

        float tongDoanhThu = 0;
        if (check == 1) {
            tongDoanhThu = thongKeRepo.tongDoanhThu();
        } else if (check == 2) {
            tongDoanhThu = thongKeRepo.tongDoanhThuHomNay();
        } else if (check == 3) {
            tongDoanhThu = thongKeRepo.tongDoanhThuThangNay();
        } else if (check == 4) {
            tongDoanhThu = thongKeRepo.tongDoanhThuNamNay();
        } else if (check == 5) {
            tongDoanhThu = thongKeRepo.tongDoanhThuTrongKhoang(txtNgayBD.getDate(), txtNgayKT.getDate());
        }
        lblDoanhThu.setText(df.format(tongDoanhThu) + "   VND");
    }

    private void tongHoaDon(int check) {//1 từ trước đến nay, 2 hôm nay, 3 tháng này, 4 năm nay, 5 tìm kiếm trong khoảng ngày
        int tongHoaDon = 0;
        if (check == 1) {
            tongHoaDon = thongKeRepo.tongSoHoaDon();
        } else if (check == 2) {
            tongHoaDon = thongKeRepo.tongSoHoaDonHomNay();
        } else if (check == 3) {
            tongHoaDon = thongKeRepo.tongSoHoaDonThangNay();
        } else if (check == 4) {
            tongHoaDon = thongKeRepo.tongSoHoaDonNamNay();
        } else if (check == 5) {
            tongHoaDon = thongKeRepo.tongSoHoaDonTrongKhoang(txtNgayBD.getDate(), txtNgayKT.getDate());
        }
        lblTongHD.setText(String.valueOf(tongHoaDon));
    }

    private void tongSoSanPham(int check) {//1 từ trước đến nay, 2 hôm nay, 3 tháng này, 4 năm nay, 5 tìm kiếm trong khoảng ngày
        int tongSP = 0;
        if (check == 1) {
            tongSP = thongKeRepo.tongSoLuongSanPhamDaBan();
        } else if (check == 2) {
            tongSP = thongKeRepo.tongSoLuongSanPhamDaBanHomNay();
        } else if (check == 3) {
            tongSP = thongKeRepo.tongSoLuongSanPhamDaBanThangNay();
        } else if (check == 4) {
            tongSP = thongKeRepo.tongSoLuongSanPhamDaBanNamNay();
        } else if (check == 5) {
            tongSP = thongKeRepo.tongSoLuongSanPhamDaTrongKhoang(txtNgayBD.getDate(), txtNgayKT.getDate());
        }
        lblTongSP.setText(String.valueOf(tongSP));
    }

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // Lấy ngày hôm nay
        Date ngayHienTai = new Date();

        // Lấy ngày trực tiếp từ JDateChooser
        Date ngayBD = txtNgayBD.getDate();
        Date ngayKT = txtNgayKT.getDate();

        // Kiểm tra nếu ngày bắt đầu hoặc ngày kết thúc lớn hơn ngày hôm nay
        if (ngayBD.after(ngayHienTai)) {
            // Hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được chọn sau ngày hôm nay!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ngayKT.after(ngayHienTai)) {
            // Hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không được chọn sau ngày hôm nay!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Kiểm tra nếu ngayBD lớn hơn hoặc bằng ngayKT
        if (ngayBD.after(ngayKT)) {
            // Hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhở hơn ngày kết thúc và ngược lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        doanhThu(5);
        tongHoaDon(5);
        tongSoSanPham(5);
        bieuDo(5);
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bieuDoPanel;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblTongHD;
    private javax.swing.JLabel lblTongSP;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    // End of variables declaration//GEN-END:variables
}
